import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { chromium } from 'playwright';

const appUrl = process.env.APP_URL || 'http://127.0.0.1:5173';
const imagePath = process.env.OUTFIT_IMAGE
  ? path.resolve(process.env.OUTFIT_IMAGE)
  : path.resolve('../dataset/sample-outfit.jpg');
const userId = process.env.USER_ID || 'demo-user';
const occasionId = process.env.OCCASION_ID || 'party';
const artifactsDir = path.resolve(process.cwd(), 'artifacts');

fs.mkdirSync(artifactsDir, { recursive: true });

if (!fs.existsSync(imagePath)) {
  const fallbackImage = path.join(artifactsDir, 'autogenerated-outfit.png');
  // Tiny valid PNG (1x1 pixel) as default upload fixture.
  const onePxPngBase64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO3Z6wAAAABJRU5ErkJggg==';
  fs.writeFileSync(fallbackImage, Buffer.from(onePxPngBase64, 'base64'));
  console.warn(`OUTFIT_IMAGE not found. Using autogenerated fallback at ${fallbackImage}`);
}
const uploadImagePath = fs.existsSync(imagePath) ? imagePath : path.join(artifactsDir, 'autogenerated-outfit.png');

const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });

try {
  await page.goto(appUrl, { waitUntil: 'networkidle' });
  await page.screenshot({ path: path.join(artifactsDir, '01-home.png'), fullPage: true });

  // Open profile panel and set user id.
  await page.getByRole('button', { name: /profile/i }).click();
  const userIdInput = page.locator('input.input').first();
  await userIdInput.fill(userId);

  // Upload image and choose occasion.
  await page.locator('#image-file-input').setInputFiles(uploadImagePath);
  await page.locator(`#occasion-${occasionId}`).click();
  await page.screenshot({ path: path.join(artifactsDir, '02-uploaded.png'), fullPage: true });

  // Run analysis and wait for results.
  await page.locator('#btn-analyse').click();
  await page.waitForSelector('text=Upgraded Preview', { timeout: 120000 });
  await page.screenshot({ path: path.join(artifactsDir, '03-results.png'), fullPage: true });

  // Optional: capture recommendation interaction if present.
  const likeBtn = page.locator('#recommendation-card-0 button').first();
  if (await likeBtn.count()) {
    await likeBtn.click();
    await page.screenshot({ path: path.join(artifactsDir, '04-feedback-clicked.png'), fullPage: true });
  }
